### ISSUE TITLE
Wireguard VPN for zimfarm hosts on dynamic IPs to tunnel traffic through a static IP host

### ISSUE THREAD

**Issue by pirate** [openzim/zimfarm#488]
I've been working on a solution for my closet-based Zimfarm host to connect to a VPS server with a static IP.
It uses wireguard to tunnel the traffic of a container through a Wireguard VPN host on a remote server.

This is the docker setup on the "client" (zimfarm worker):
```yaml
version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg0.conf:ro

  zimfarm:
    image: openzim/zimfarm
    network_mode: 'service:wireguard'
	volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/zimfarm:/data
```

This is the standard recommended way to run a container's internet traffic through wireguard, though there are some other more difficult ways involving [modifying IPtables on the host](https://saasbootstrap.com/how-to-setup-a-vpn-with-wireguard-that-only-routes-traffic-from-a-specific-docker-container-or-specific-ip/) (which I'd rather not do on my machine, and is also difficult because the containers are spawned dynamically so DHCP+wg-dynamic or some other solution must be used to give each container an IP). 

The issue is that `zimfarm` doesn't work as a single container, it instead takes control of docker on the host machine to spawn multiple other containers, which means it's more difficult to get it to run all those containers through wireguard.

Possible solutions:

- make zimfarm able to run as a single container (probably infeasible based on its architecture)
- make zimfarm able to run using docker-in-docker (maybe buggy / slow?)
- add an option to zimfarm so that it can spawn all of its containers in a docker-compose project with `network_mode: 'service:wireguard'` on each, such that all their traffic runs through the wireguard container's networking stack
- use IPtables and Wireguard on the zimfarm worker host outside of docker to force docker traffic into a wireguard tunnel (last resort)

**Comment by pirate** [comment]
How much transfer per month is typical for a zimfarm worker? Would it exceed 1TB/mo?

I ask because I'm going to set up a VPN bounce machine to try and get my zimfarm rack server up again, and am wondering how much to budget for bandwidth.

**Comment by kelson42** [comment]
@pirate Good news, but question hard if not impossible to answer. It depends... but if it ever goes over 1TB, it should really not be from that much.

**Comment by rgaudin** [comment]
Looked at the AWS-hosted worker we had and the last bill says:

Item | Value
------------ | -------------
data transfer in per month | 1,019.211 GB
first 1 GB of data transferred out per month | 0.949 GB
regional data transfer - in/out/between EC2 AZs or using elastic IPs or ELB | 0.116 GB
first 10 TB / month data transfer out beyond the global free tier | 269.521 GB

**Comment by rgaudin** [comment]
This dates back from August.

**Comment by pirate** [comment]
Ok, I was thinking of using DigitalOcean which is 1TB for free, with $0.02 USD/GB after that. Hoping it's not too much higher because then it goes from a $5/mo project to a $20+/mo project. I will keep looking at alternative hosting providers, maybe I can find one with free bandwidth up to 2TB.

**Comment by pirate** [comment]
Bumping this because I think many more people would be able to run zimfarm if it were usable as a `docker-compose.yml` project similar to ArchiveTeam's Archive Warrior system that many people run: https://github.com/ArchiveTeam/warrior-dockerfile

```yaml
services:
  archivewarrior:
    image: archiveteam/warrior-dockerfile
    ports:
      - 8001:8001
    environment:
      - SELECTED_PROJECT=auto
```

Last I checked this was difficult because zimfarm relies on being able to spawn multiple Docker containers, and that process is currently done a script outside Docker.

Does there exist a container that can run that script to manage spawning other containers (using `/var/run/docker.sock`)? If so can I help make it? Really want to help get to this point:

```yaml
  zimfarm:
    image: openzim/zimfarm
    network_mode: 'service:wireguard'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/zimfarm:/data
```

I think I could help get you a decent number of people running this ^ once we get it to be this easy (even considering the >1TB bandwidth, CPU, and fixed IP requirements).
